Add pattern catalog page to MLIR website (#230)
This PR adds a basic pattern-search index to the MLIR website.

## Features:

- Autocomplete operation name on search input
- Links to GitHub search for the class name in `path:mlir`
- Clicking on a search result shows a popup with the class and all the
operations it touches (each of which is a link to the search)
- Filters by C++ namespace of the pattern and the "modification type"
(insert, remove, replace) the pattern applies to that op
- Support regex inputs for operation name (e.g., `.*\.for`)

## Screenshots

<img width="1580" height="1308" alt="image"
src="https://github.com/user-attachments/assets/d70f60cc-de86-4d3d-ad13-e0b43e8d57a3"
/>


<img width="1598" height="1010" alt="image"
src="https://github.com/user-attachments/assets/eaf25e57-720b-4022-9a3a-d4aa114f969b"
/>

---------

Co-authored-by: Jeremy Kun <j2kun@users.noreply.github.com>
Co-authored-by: Mehdi Amini <joker.eph@gmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,7 +31,7 @@ jobs:
       run: ./mlir-www-helper.sh --help
 
     - name: Install dependencies
-      run: sudo apt-get install doxygen graphviz
+      run: sudo apt-get install doxygen graphviz python3
 
     - name: Clone LLVM repo
       uses: actions/checkout@v3
@@ -44,8 +44,10 @@ jobs:
       run: |
         mkdir llvm_src/build
         cd llvm_src/build
+        # Assert mode is needed for the pattern search index
         cmake ../llvm \
           -DCMAKE_BUILD_TYPE=Release \
+          -DLLVM_ENABLE_ASSERTIONS=ON \
           -DLLVM_ENABLE_PROJECTS=mlir \
           -DLLVM_TARGETS_TO_BUILD="host" \
           -DMLIR_INCLUDE_DOCS="true" \
@@ -54,6 +56,25 @@ jobs:
 
     - name: Install docs
       run: ./mlir-www-helper.sh --install-docs "llvm_src" "website"
+
+    - name: Build pattern search index
+      run: |
+        cd llvm_src/build
+        # Run the tests once to ensure they are passing.
+        # The next run used to generate the patterns log is disabling error checking. This first
+        # run will ensure we don't generate the website when tests are broken.
+        make -j$(nproc) check-mlir
+        echo "finished building tests"
+        # ignore nonzero exit codes in this command, since MLIR_GENERATE_PATTERN_CATALOG
+        # implicitly enables`--mlir-disable-threading` which some tests are incompatible with.
+        { MLIR_GENERATE_PATTERN_CATALOG=1 bin/llvm-lit -j$(nproc) -v -a tools/mlir/test || true ; } \
+          | grep '# | \[pattern-logging-listener' \
+          | sed 's/# | \[pattern-logging-listener:[0-9]*\] PatternLoggingListener.cpp:[0-9]* //g' \
+          | sort | uniq > $HOME/pattern_catalog.txt
+        # back to mlir-www root
+        cd ../..
+        head $HOME/pattern_catalog.txt
+        python3 build_pattern_catalog_index.py $HOME/pattern_catalog.txt website/static/pattern-search/pattern-index.json
 
     - name: Setup Hugo
       uses: peaceiris/actions-hugo@v2
